const catchAsync = require('./../utilities/catchAsync');
const AppError = require('./../utilities/AppError');

exports.deleteDoc = Model => catchAsync(async (req, res, next) => {
    const doc = await Model.findByIdAndDelete(req.params.id);

    if (!doc) {
        return next(new AppError('No document found with that ID', 404));
    }

    res.status(204).json({
        status: 'success',
        data: null
    });
});